SET V_JAVA_HOME=C:/Program Files/Java/jdk1.8.0_131
SET V_ANDROID_SDK_ROOT=F:/ANDROID/Android_SDK
SET V_DEV_HOME=.
SET V_ANDROID_BUILD_TOOLS=%V_ANDROID_SDK_ROOT%/build-tools/26.0.0
SET V_ANDROID_PLATFORMS=%V_ANDROID_SDK_ROOT%/platforms/android-19
SET V_ANDROID_PLATFORM_TOOLS=%V_ANDROID_SDK_ROOT%/platform-tools